services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\Builder\ContextDefinitionBuilderInterface: '@DynamicSearchBundle\Builder\ContextDefinitionBuilder'
    DynamicSearchBundle\Builder\ContextDefinitionBuilder: ~
