services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\Command\SearchCommand:
        tags:
            - { name: console.command }
