services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    DynamicSearchBundle\Controller\SearchController:
        tags:
            - 'controller.service_arguments'

    DynamicSearchBundle\Controller\SearchFrontendController:
        tags:
            - 'controller.service_arguments'

    DynamicSearchBundle\Controller\Admin\SettingsController:
        tags:
            - 'controller.service_arguments'