services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\Generator\IndexDocumentGeneratorInterface: '@DynamicSearchBundle\Generator\IndexDocumentGenerator'
    DynamicSearchBundle\Generator\IndexDocumentGenerator: ~