services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\Validator\ResourceValidatorInterface: '@DynamicSearchBundle\Validator\ResourceValidator'
    DynamicSearchBundle\Validator\ResourceValidator: ~
