services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\Provider\Extension\ProviderBundleLocatorInterface: '@DynamicSearchBundle\Provider\Extension\ProviderBundleLocator'
    DynamicSearchBundle\Provider\Extension\ProviderBundleLocator:
        arguments:
            $availableBundles: '%kernel.bundles%'
