services:

    DynamicSearchBundle\Runner\AbstractRunner:
        public: false
        abstract: true
        calls:
            - [setLogger, ['@DynamicSearchBundle\Logger\Logger']]
            - [setConfiguration, ['@DynamicSearchBundle\Configuration\Configuration']]
            - [setContextDefinitionBuilder, ['@DynamicSearchBundle\Builder\ContextDefinitionBuilder']]
            - [setDataManager, ['@DynamicSearchBundle\Manager\DataManager']]
            - [setIndexManager, ['@DynamicSearchBundle\Manager\IndexManager']]
            - [setIndexDocumentGenerator, ['@DynamicSearchBundle\Generator\IndexDocumentGenerator']]

    DynamicSearchBundle\Runner\ContextRunnerInterface: '@DynamicSearchBundle\Runner\ContextRunner'
    DynamicSearchBundle\Runner\ContextRunner:
        parent: DynamicSearchBundle\Runner\AbstractRunner
        autowire: true
        autoconfigure: false
        public: false

    DynamicSearchBundle\Runner\ResourceRunnerInterface: '@DynamicSearchBundle\Runner\ResourceRunner'
    DynamicSearchBundle\Runner\ResourceRunner:
        parent: DynamicSearchBundle\Runner\AbstractRunner
        autowire: true
        autoconfigure: false
        public: false

    DynamicSearchBundle\Runner\SimpleRunnerInterface: '@DynamicSearchBundle\Runner\SimpleRunner'
    DynamicSearchBundle\Runner\SimpleRunner:
        parent: DynamicSearchBundle\Runner\AbstractRunner
        autowire: true
        autoconfigure: false
        public: false

