services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # configuration
    DynamicSearchBundle\Configuration\ConfigurationInterface: '@DynamicSearchBundle\Configuration\Configuration'
    DynamicSearchBundle\Configuration\Configuration: ~

    DynamicSearchBundle\Tool\Install:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('DynamicSearchBundle')"
