parameters:
    dynamic_search.queue.table_name: messenger_dynamic_search

framework:
    messenger:
        transports:
            dynamic_search_queue:
                dsn: 'microsecs-doctrine://default'
                options:
                    table_name: '%dynamic_search.queue.table_name%'
        routing:
            DynamicSearchBundle\Queue\Message\QueueResourceMessage: dynamic_search_queue
            DynamicSearchBundle\Queue\Message\ProcessResourceMessage: dynamic_search_queue
        buses:
            dynamic_search.bus: ~

services:
    DynamicSearchBundle\Queue\Transport\ExtendedDoctrineTransportFactory:
        arguments:
            - '@Doctrine\Persistence\ConnectionRegistry'
        tags: [ messenger.transport_factory ]
